name: Build Bitbucket Bot application

env:
  DOCKERHUB_USER: devopsiaci
  DOCKERHUB_REPO: bitbucket-bot
  GHCR_REGISTRY: ghcr.io
  GHCR_REPO: ${{ github.repository }}

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic_release
        with:
          dry_run: true
          branch: main
          tag_format: ${version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}
          labels: |
            org.opencontainers.image.maintainer=ialejandro
            org.opencontainers.image.title=Bitbucket Bot
            org.opencontainers.image.description=Bitbucket Bot to Google Chat (Spaces)
            org.opencontainers.image.vendor=DevOps IA
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=sha,enable=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: "[DOCKERHUB] Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "[GHCR] Log in to the Container registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker image"
        id: push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: "[DOCKERHUB] Update Docker registry description"
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}

      - name: "[GHCR] Generate artifact"
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPO }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
